
/:
  controller: Main
  action: default
  auth: false

/admin:
  controller: Security
  action: default
  auth: true

/dashboard:
  controller: Security
  action: admin
  auth: false

/stats:
  controller: Main
  action: stats
  auth: false

/settings:
  controller: Main
  action: settings
  auth: false

/register:
  controller: Security
  action: register
  auth: false

/login:
  controller: Security
  action: login
  auth: false

/logout:
  controller: Security
  action: logout
  auth: true

/home:
  controller: Main
  action: home
  auth: false
  role: user

/training:
  controller: Training
  action: training
  auth: false

/training/options:
  controller: Training
  action: trainingOptions
  auth: false

/model:
  controller: Front
  action: model
  auth: false

/users:
  controller: Main
  action: users
  auth: false

/forget-password:
  controller: Security
  action: forgetPassword
  auth: false

/admin-user:
  controller: User
  action: user
  auth: false

/admin-user/update:
  controller: User
  action: updateUser
  auth: false
