
/:
  controller: Main
  action: default
  auth: false

/admin:
  controller: Security
  action: default
  auth: true

/dashboard:
  controller: Security
  action: admin
  auth: false

/stats:
  controller: Main
  action: stats
  auth: false

/settings:
  controller: Main
  action: settings
  auth: false

/s-inscrire:
  controller: Security
  action: register
  auth: false

/se-connecter:
  controller: Security
  action: login
  auth: false

/login:
  controller: Security
  action: login
  auth: false

/se-deconnecter:
  controller: Security
  action: logout
  auth: true

/home:
  controller: Main
  action: home
  auth: false

/training:
  controller: Main
  action: training
  auth: false

/pages:
  controller: Pages
  action: pages
  auth: false


