

/admin:
  controller: Security
  action: default
  auth: true
  role: admin

/dashboard:
  controller: Security
  action: admin
  auth: true
  role: admin

/stats:
  controller: Main
  action: stats
  auth: true
  role: admin

/settings:
  controller: Main
  action: settings
  auth: true
  role: admin

/register:
  controller: Security
  action: register
  auth: false

/login:
  controller: Security
  action: login
  auth: false

/logout:
  controller: Security
  action: logout
  auth: true

/home:
  controller: Main
  action: home
  auth: false
  role: user

/training:
  controller: Training
  action: training
  auth: true
  role: admin

/training/options:
  controller: Training
  action: trainingOptions
  auth: true
  role: admin

/training/update:
  controller: Training
  action: trainingUpdate
  auth: true
  role: admin

/training/delete:
  controller: Training
  action: trainingDelete
  auth: true
  role: admin

/training/visible:
  controller: Training
  action: trainingVisible
  auth: true
  role: admin

/forget-password:
  controller: Security
  action: forgetPassword
  auth: false

/admin-user:
  controller: User
  action: user
  auth: true
  role: admin

/admin-user/delete:
  controller: User
  action: deleteUser
  auth: true
  role: admin

/lesson/update:
  controller: Part
  action: updateLesson
  auth: true
  role: admin

/lesson/delete:
  controller: Lessons
  action: deleteLesson
  auth: true
  role: admin

/part/delete:
  controller: Part
  action: deletePart
  auth: true
  role: admin

/part/sort:
  controller: Part
  action: sortPart
  auth: true
  role: admin

/pages:
  controller: Page
  action: showPages
  auth: true
  role: admin

/page-creator:
  controller: Page
  action: createPage
  auth: true
  role: admin

/page/render:
  controller: Page
  action: renderPage
  auth: true
  role: admin

/page/update:
  controller: Page
  action: updatePage
  auth: true
  role: admin

/navbar:
  controller: Navbar
  action: navEdit
  auth: true
  role: admin

/courses:
  controller: Training
  action: list
  auth: false

/lesson/display:
  controller: Lessons
  action: display
  auth: false

/installer-delete:
  controller: Security
  action: uninstallInstaller
  auth: false