
/:
  controller: Main
  action: default
  auth: false

/admin:
  controller: Security
  action: default
  auth: true

/dashboard:
  controller: Security
  action: admin
  auth: false

/stats:
  controller: Main
  action: stats
  auth: false

/settings:
  controller: Main
  action: settings
  auth: false

/register:
  controller: Security
  action: register
  auth: false

/login:
  controller: Security
  action: login
  auth: false

/logout:
  controller: Security
  action: logout
  auth: true

/home:
  controller: Main
  action: home
  auth: false
  role: user

/training:
  controller: Main
  action: training
  auth: false

/lesson:
  controller: Training
  action: lesson
  auth: false

/pages:
  controller: Pages
  action: pages
  auth: false

/model:
  controller: Front
  action: model
  auth: false
